name: Update Dependabot

on:
  workflow_dispatch:
  push:
    paths:
      - .github/dependabot/**  # Trigger on changes in the .github/dependabot directory

permissions:
  contents: write

jobs:
  Update-Dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # or another version you need

      - name: Install dependencies
        run: |
          npm install base-64
          npm install @actions/github
          npm install @octokit/rest@18.0.0
          npm install @actions/core

      - name: Run dependabot.js script to update dependabot.yml in target repositories
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # Ensure the token is available
        run: node .github/scripts/dependabot.js