---
name: Lint

on:
  push:
  pull_request:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      VALIDATE_JSCPD_ALL_CODEBASE:
        required: false
        type: boolean
        default: false
      VALIDATE_ANSIBLE:
        required: false
        type: boolean
        default: false
      VALIDATE_ARM:
        required: false
        type: boolean
        default: false
      VALIDATE_BASH:
        required: false
        type: boolean
        default: false
      VALIDATE_BASH_EXEC:
        required: false
        type: boolean
        default: false
      VALIDATE_CPP:
        required: false
        type: boolean
        default: false
      VALIDATE_CLANG_FORMAT:
        required: false
        type: boolean
        default: false
      VALIDATE_CLOJURE:
        required: false
        type: boolean
        default: false
      VALIDATE_CLOUDFORMATION:
        required: false
        type: boolean
        default: false
      VALIDATE_COFFEESCRIPT:
        required: false
        type: boolean
        default: false
      VALIDATE_CSHARP:
        required: false
        type: boolean
        default: false
      VALIDATE_CSS:
        required: false
        type: boolean
        default: false
      VALIDATE_DART:
        required: false
        type: boolean
        default: false
      VALIDATE_DOCKERFILE_HADOLINT:
        required: false
        type: boolean
        default: false
      VALIDATE_EDITORCONFIG:
        required: false
        type: boolean
        default: false
      VALIDATE_ENV:
        required: false
        type: boolean
        default: false
      VALIDATE_GHERKIN:
        required: false
        type: boolean
        default: false
      VALIDATE_GITHUB_ACTIONS:
        required: false
        type: boolean
        default: false
      VALIDATE_GITLEAKS:
        required: false
        type: boolean
        default: false
      VALIDATE_GO:
        required: false
        type: boolean
        default: false
      VALIDATE_GOOGLE_JAVA_FORMAT:
        required: false
        type: boolean
        default: false
      VALIDATE_GROOVY:
        required: false
        type: boolean
        default: false
      VALIDATE_HTML:
        required: false
        type: boolean
        default: false
      VALIDATE_JAVA:
        required: false
        type: boolean
        default: false
      VALIDATE_JAVASCRIPT_ES:
        required: false
        type: boolean
        default: false
      VALIDATE_JAVASCRIPT_STANDARD:
        required: false
        type: boolean
        default: false
      VALIDATE_JSCPD:
        required: false
        type: boolean
        default: false
      VALIDATE_JSON:
        required: false
        type: boolean
        default: false
      VALIDATE_JSX:
        required: false
        type: boolean
        default: false
      VALIDATE_KOTLIN:
        required: false
        type: boolean
        default: false
      VALIDATE_KOTLIN_ANDROID:
        required: false
        type: boolean
        default: false
      VALIDATE_KUBERNETES_KUBECONFORM:
        required: false
        type: boolean
        default: false
      VALIDATE_LATEX:
        required: false
        type: boolean
        default: false
      VALIDATE_LUA:
        required: false
        type: boolean
        default: false
      VALIDATE_MARKDOWN:
        required: false
        type: boolean
        default: false
      VALIDATE_NATURAL_LANGUAGE:
        required: false
        type: boolean
        default: false
      VALIDATE_OPENAPI:
        required: false
        type: boolean
        default: false
      VALIDATE_PERL:
        required: false
        type: boolean
        default: false
      VALIDATE_PHP:
        required: false
        type: boolean
        default: false
      VALIDATE_PHP_BUILTIN:
        required: false
        type: boolean
        default: false
      VALIDATE_PHP_PHPCS:
        required: false
        type: boolean
        default: false
      VALIDATE_PHP_PHPSTAN:
        required: false
        type: boolean
        default: false
      VALIDATE_PHP_PSALM:
        required: false
        type: boolean
        default: false
      VALIDATE_POWERSHELL:
        required: false
        type: boolean
        default: false
      VALIDATE_PROTOBUF:
        required: false
        type: boolean
        default: false
      VALIDATE_PYTHON:
        required: false
        type: boolean
        default: false
      VALIDATE_PYTHON_BLACK:
        required: false
        type: boolean
        default: false
      VALIDATE_PYTHON_FLAKE8:
        required: false
        type: boolean
        default: false
      VALIDATE_PYTHON_ISORT:
        required: false
        type: boolean
        default: false
      VALIDATE_PYTHON_MYPY:
        required: false
        type: boolean
        default: false
      VALIDATE_PYTHON_PYLINT:
        required: false
        type: boolean
        default: false
      VALIDATE_R:
        required: false
        type: boolean
        default: false
      VALIDATE_RAKU:
        required: false
        type: boolean
        default: false
      VALIDATE_RENOVATE:
        required: false
        type: boolean
        default: false
      VALIDATE_RUBY:
        required: false
        type: boolean
        default: false
      VALIDATE_RUST_2015:
        required: false
        type: boolean
        default: false
      VALIDATE_RUST_2018:
        required: false
        type: boolean
        default: false
      VALIDATE_RUST_2021:
        required: false
        type: boolean
        default: false
      VALIDATE_RUST_CLIPPY:
        required: false
        type: boolean
        default: false
      VALIDATE_SCALAFMT:
        required: false
        type: boolean
        default: false
      VALIDATE_SHELL_SHFMT:
        required: false
        type: boolean
        default: false
      VALIDATE_SNAKEMAKE_LINT:
        required: false
        type: boolean
        default: false
      VALIDATE_SNAKEMAKE_SNAKEFMT:
        required: false
        type: boolean
        default: false
      VALIDATE_STATES:
        required: false
        type: boolean
        default: false
      VALIDATE_SQL:
        required: false
        type: boolean
        default: false
      VALIDATE_SQLFLUFF:
        required: false
        type: boolean
        default: false
      VALIDATE_TEKTON:
        required: false
        type: boolean
        default: false
      VALIDATE_TERRAFORM_FMT:
        required: false
        type: boolean
        default: false
      VALIDATE_TERRAFORM_TERRASCAN:
        required: false
        type: boolean
        default: false
      VALIDATE_TERRAFORM_TFLINT:
        required: false
        type: boolean
        default: false
      VALIDATE_TERRAGRUNT:
        required: false
        type: boolean
        default: false
      VALIDATE_TSX:
        required: false
        type: boolean
        default: false
      VALIDATE_TYPESCRIPT_ES:
        required: false
        type: boolean
        default: false
      VALIDATE_TYPESCRIPT_STANDARD:
        required: false
        type: boolean
        default: false
      VALIDATE_XML:
        required: false
        type: boolean
        default: false
      VALIDATE_YAML:
        required: false
        type: boolean
        default: false

jobs:
  Lint:
    uses: dennykorsukewitz/dennykorsukewitz/.github/workflows/reusable.lint.yml@dev
