---
name: Lint

on:
  push:
  pull_request:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      VALIDATE_BASH:
        required: false
        type: boolean
        default: false
      VALIDATE_CSS:
        required: false
        type: boolean
        default: false
      VALIDATE_GITHUB_ACTIONS:
        required: false
        type: boolean
        default: false
      VALIDATE_HTML:
        required: false
        type: boolean
        default: false
      VALIDATE_JAVASCRIPT_ES:
        required: false
        type: boolean
        default: false
      VALIDATE_JAVASCRIPT_STANDARD:
        required: false
        type: boolean
        default: false
      VALIDATE_JSON:
        required: false
        type: boolean
        default: false
      VALIDATE_MARKDOWN:
        required: false
        type: boolean
        default: false
      VALIDATE_XML:
        required: false
        type: boolean
        default: false
      VALIDATE_YAML:
        required: false
        type: boolean
        default: false

jobs:
  Lint:
    uses: dennykorsukewitz/dennykorsukewitz/.github/workflows/reusable.lint.yml@dev
