# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (“At 00:00.”)
  schedule:
    # "0 0 * * *" (UTC) = "0 1 * * *" (Germany)
    - cron: "0 0 * * *"
  # push:
  #   branches: ["dev", "main"]
  workflow_dispatch:

jobs:

  Personal:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout dennykorsukewitz
        uses: actions/checkout@v4
        env:
          fetch-depth: "1"
      - name: Personal
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: .github/metrics/personal.svg
          output_action: none

          # Options
          user: dennykorsukewitz
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_timezone: Europe/Berlin
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_introduction: yes
          plugin_introduction_title: yes
          # plugin_isocalendar: yes
          # plugin_isocalendar_duration: full-year
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_repositories: yes
          plugin_repositories_featured: znuny/znuny, karldaeubel/PenAndPaperFloorplanner, zammad/zammad
          plugin_repositories_order: featured, pinned, starred, random
      - name: Move Metrics Renders
        run: |
          set +e
          ls -alih /metrics_renders
          ls -alih /metrics_renders/.github/
          ls -alih /metrics_renders/.github/metrics/
          ls -alih /metrics_renders/.github/metrics/personal.svg
          sudo cp -rf /metrics_renders/* ./
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metrics-svg-Personal
          path: .github/metrics/personal.svg 

  # Languages:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - name: Checkout dennykorsukewitz
  #       uses: actions/checkout@v4
  #       env:
  #         fetch-depth: "1"
  #     - name: Languages Indepth
  #       uses: lowlighter/metrics@latest
  #       with:
  #         token: ${{ secrets.METRICS_TOKEN }}
  #         filename: .github/metrics/languages.indepth.svg
  #         output_action: none

  #         # Options
  #         base: ""
  #         plugin_languages: yes
  #         plugin_languages_ignored: >-
  #           tex, less, dockerfile, makefile, qmake, lex, cmake,
  #           gnuplot
  #         plugin_languages_indepth: yes
  #         plugin_languages_details: lines, bytes-size, percentage
  #         plugin_languages_limit: 8
  #         plugin_languages_analysis_timeout: 60
  #     - name: Move Metrics Renders
  #       run: |
  #         set +e
  #         sudo cp -rf /metrics_renders/* ./
  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: metrics-svg-Languages
  #         path: .github/metrics/languages.indepth.svg

  Commit-Calendar-Isometric:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout dennykorsukewitz
        uses: actions/checkout@v4
        env:
          fetch-depth: "1"
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: none
          filename: .github/metrics/commit-calendar.isometric.svg

          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - name: Move Metrics Renders
        run: |
          set +e
          sudo cp -rf /metrics_renders/* ./
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metrics-svg-Commit-Calendar-Isometric
          path: .github/metrics/commit-calendar.isometric.svg

  Commit-Calendar-Flat:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout dennykorsukewitz
        uses: actions/checkout@v4
        env:
          fetch-depth: "1"
      - name: Commit current year calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: none
          filename: .github/metrics/commit-calendar.current.svg

          # Options
          base: ""
          plugin_calendar: yes

      - name: Commit current year calendar total
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: none
          filename: .github/metrics/commit-calendar.total.svg

          # Options
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0
      - name: Move Metrics Renders
        run: |
          set +e
          sudo cp -rf /metrics_renders/* ./
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metrics-svg-Commit-Calendar-Flat
          path: |
            .github/metrics/commit-calendar.current.svg
            .github/metrics/commit-calendar.total.svg

  Comment-Reactions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout dennykorsukewitz
        uses: actions/checkout@v4
        env:
          fetch-depth: "1"
      - name: Comment Reactions
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: .github/metrics/comment.reactions.svg
          output_action: none

          # Options
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 1000
          plugin_reactions_limit_issues: 1000
          plugin_reactions_limit_discussions: 1000
          plugin_reactions_limit_discussions_comments: 1000
          plugin_reactions_details: percentage
      - name: Move Metrics Renders
        run: |
          set +e
          sudo cp -rf /metrics_renders/* ./
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metrics-svg-Comment-Reactions
          path: .github/metrics/comment.reactions.svg

  Sponsors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout dennykorsukewitz
        uses: actions/checkout@v4
        env:
          fetch-depth: "1"
      - name: Sponsors
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: .github/metrics/sponsors.svg
          output_action: none

          # Options
          base: ""
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, about, list
          plugin_sponsors_past: yes
          plugin_sponsors_title: "Sponsor Me!"
      - name: Move Metrics Renders
        run: |
          set +e
          sudo cp -rf /metrics_renders/* ./
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metrics-svg-Sponsors
          path: .github/metrics/sponsors.svg

  Stargazers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout dennykorsukewitz
        uses: actions/checkout@v4
        env:
          fetch-depth: "1"
      - name: Stargazers graph
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: .github/metrics/stargazers.graph.svg
          output_action: none

          # Options
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_days: 0
          plugin_stargazers_charts_type: graph
      - name: Move Metrics Renders
        run: |
          set +e
          sudo cp -rf /metrics_renders/* ./
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metrics-svg-Stargazers
          path: .github/metrics/stargazers.graph.svg

  NPM:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout dennykorsukewitz
        uses: actions/checkout@v4
        env:
          fetch-depth: "1"
      - name: Get NPM data
        run: ./.github/workflows/metrics/npm.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metrics-data-NPM
          path: |
            .github/metrics/data/npm-total.json
            .github/metrics/data/npm-daily.json

  Stars:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout dennykorsukewitz
        uses: actions/checkout@v4
        env:
          fetch-depth: "1"
      - name: Get GitHub data
        run: ./.github/workflows/metrics/github.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metrics-data-Stars
          path: |
            .github/metrics/data/github-stars.json
            .github/metrics/data/github-stars-data.json

  Sublime:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout dennykorsukewitz
        uses: actions/checkout@v4
        env:
          fetch-depth: "1"
      - name: Get Sublime data
        run: ./.github/workflows/metrics/sublime.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metrics-data-Sublime
          path: |
            .github/metrics/data/sublime-total.json
            .github/metrics/data/sublime-daily.json

  VSCode:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
      VSC_PAT: ${{ secrets.VSC_PAT }}
    steps:
      - name: Checkout dennykorsukewitz
        uses: actions/checkout@v4
        env:
          fetch-depth: "1"
      - name: Get VSCode data
        run: ./.github/workflows/metrics/vscode.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metrics-data-VSCode
          path: |
            .github/metrics/data/vscode-total.json
            .github/metrics/data/vscode-daily.json

  Daily:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
      VSC_PAT: ${{ secrets.VSC_PAT }}
    needs:
      [
        NPM,
        Sublime,
        VSCode,
      ]
    if: ${{ always() }}
    steps:
      - name: Checkout dennykorsukewitz
        uses: actions/checkout@v4
        env:
          fetch-depth: "1"
      - name: Download artifact metrics-data
        uses: actions/download-artifact@v4
        with:
          pattern: metrics-data-*
          path: .github/metrics/data/
          merge-multiple: true
      - name: Get Daily data
        run: ./.github/workflows/metrics/daily.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metrics-data-Daily
          path: .github/metrics/data/daily.json

  Download-And-Commit:
    name: "Download and Commit"
    runs-on: ubuntu-latest
    needs:
      [
        Personal,
        # Languages,
        Commit-Calendar-Isometric,
        Commit-Calendar-Flat,
        Comment-Reactions,
        Sponsors,
        Stargazers,
        Daily,
        NPM,
        Stars,
        Sublime,
        VSCode,
      ]
    if: ${{ always() }}
    steps:
      - name: Checkout dennykorsukewitz
        uses: actions/checkout@v4
        env:
          fetch-depth: "1"
      - name: Git Pull
        run: git pull
      - name: Download artifact metrics-svg
        uses: actions/download-artifact@v4
        with:
          pattern: metrics-svg-*
          path: .github/metrics/
          merge-multiple: true
      - name: Download artifact metrics-data
        uses: actions/download-artifact@v4
        with:
          pattern: metrics-data-*
          path: .github/metrics/data/
          merge-multiple: true
      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updated Metrics."
