---
name: Lint
# v8.5.0
# https://github.com/github/super-linter/releases/tag/v8.5.0

on:
  workflow_call:
    inputs:
      VALIDATE_ANSIBLE:
        required: false
        type: string
      VALIDATE_ARM:
        required: false
        type: string
      VALIDATE_BASH:
        required: false
        type: string
      VALIDATE_BASH_EXEC:
        required: false
        type: string
      VALIDATE_BIOME_FORMAT:
        required: false
        type: string
      VALIDATE_BIOME_LINT:
        required: false
        type: string
      VALIDATE_CPP:
        required: false
        type: string
      VALIDATE_CHECKOV:
        required: false
        type: string
        default: "false"
      VALIDATE_CLANG_FORMAT:
        required: false
        type: string
      VALIDATE_CLOJURE:
        required: false
        type: string
      VALIDATE_CLOUDFORMATION:
        required: false
        type: string
      VALIDATE_COFFEESCRIPT:
        required: false
        type: string
      VALIDATE_CSHARP:
        required: false
        type: string
      VALIDATE_CSS:
        required: false
        type: string
      VALIDATE_CSS_PRETTIER:
        required: false
        type: string
      VALIDATE_DART:
        required: false
        type: string
      VALIDATE_DOCKERFILE_HADOLINT:
        required: false
        type: string
      VALIDATE_DOTNET_SLN_FORMAT_ANALYZERS:
        required: false
        type: string
      VALIDATE_DOTNET_SLN_FORMAT_STYLE:
        required: false
        type: string
      VALIDATE_DOTNET_SLN_FORMAT_WHITESPACE:
        required: false
        type: string
      VALIDATE_EDITORCONFIG:
        required: false
        type: string
      VALIDATE_ENV:
        required: false
        type: string
      VALIDATE_GIT_COMMITLINT:
        required: false
        type: string
      VALIDATE_GIT_MERGE_CONFLICT_MARKERS:
        required: false
        type: string
      VALIDATE_GHERKIN:
        required: false
        type: string
      VALIDATE_GITHUB_ACTIONS:
        required: false
        type: string
      VALIDATE_GITHUB_ACTIONS_ZIZMOR:
        required: false
        type: string
      VALIDATE_GITLEAKS:
        required: false
        type: string
      VALIDATE_GO:
        required: false
        type: string
      VALIDATE_GO_MODULES:
        required: false
        type: string
      VALIDATE_GO_RELEASER:
        required: false
        type: string
      VALIDATE_GOOGLE_JAVA_FORMAT:
        required: false
        type: string
      VALIDATE_GRAPHQL_PRETTIER:
        required: false
        type: string
      VALIDATE_GROOVY:
        required: false
        type: string
      VALIDATE_HTML:
        required: false
        type: string
      VALIDATE_HTML_PRETTIER:
        required: false
        type: string
      VALIDATE_JAVA:
        required: false
        type: string
      VALIDATE_JAVASCRIPT_ES:
        required: false
        type: string
      VALIDATE_JAVASCRIPT_PRETTIER:
        required: false
        type: string
        default: "false"
      VALIDATE_JAVASCRIPT_STANDARD:
        required: false
        type: string
        default: "false"
      VALIDATE_JSCPD:
        required: false
        type: string
        default: "false"
      VALIDATE_JSON:
        required: false
        type: string
      VALIDATE_JSON_PRETTIER:
        required: false
        type: string
        default: "false"
      VALIDATE_JSONC:
        required: false
        type: string
      VALIDATE_JSONC_PRETTIER:
        required: false
        type: string
      VALIDATE_JSX:
        required: false
        type: string
      VALIDATE_JSX_PRETTIER:
        required: false
        type: string
      VALIDATE_JUPYTER_NBQA_BLACK:
        required: false
        type: string
      VALIDATE_JUPYTER_NBQA_FLAKE8:
        required: false
        type: string
      VALIDATE_JUPYTER_NBQA_ISORT:
        required: false
        type: string
      VALIDATE_JUPYTER_NBQA_MYPY:
        required: false
        type: string
      VALIDATE_JUPYTER_NBQA_PYLINT:
        required: false
        type: string
      VALIDATE_JUPYTER_NBQA_RUFF:
        required: false
        type: string
      VALIDATE_KOTLIN:
        required: false
        type: string
      VALIDATE_KOTLIN_ANDROID:
        required: false
        type: string
      VALIDATE_KUBERNETES_KUBECONFORM:
        required: false
        type: string
      VALIDATE_LATEX:
        required: false
        type: string
      VALIDATE_LUA:
        required: false
        type: string
      VALIDATE_MARKDOWN:
        required: false
        type: string
      VALIDATE_MARKDOWN_PRETTIER:
        required: false
        type: string
        default: "false"
      VALIDATE_NATURAL_LANGUAGE:
        required: false
        type: string
      VALIDATE_OPENAPI:
        required: false
        type: string
      VALIDATE_PERL:
        required: false
        type: string
      VALIDATE_PHP:
        required: false
        type: string
      VALIDATE_PHP_BUILTIN:
        required: false
        type: string
      VALIDATE_PHP_PHPCS:
        required: false
        type: string
      VALIDATE_PHP_PHPSTAN:
        required: false
        type: string
      VALIDATE_PHP_PSALM:
        required: false
        type: string
      VALIDATE_PRE_COMMIT:
        required: false
        type: string
      VALIDATE_POWERSHELL:
        required: false
        type: string
        default: "false"
      VALIDATE_PROTOBUF:
        required: false
        type: string
      VALIDATE_PYTHON:
        required: false
        type: string
      VALIDATE_PYTHON_BLACK:
        required: false
        type: string
      VALIDATE_PYTHON_FLAKE8:
        required: false
        type: string
      VALIDATE_PYTHON_ISORT:
        required: false
        type: string
      VALIDATE_PYTHON_MYPY:
        required: false
        type: string
        default: "false"
      VALIDATE_PYTHON_PYLINT:
        required: false
        type: string
      VALIDATE_PYTHON_RUFF:
        required: false
        type: string
      VALIDATE_PYTHON_RUFF_FORMAT:
        required: false
        type: string
      VALIDATE_R:
        required: false
        type: string
      VALIDATE_RAKU:
        required: false
        type: string
      VALIDATE_RENOVATE:
        required: false
        type: string
      VALIDATE_RUBY:
        required: false
        type: string
      VALIDATE_RUST_2015:
        required: false
        type: string
      VALIDATE_RUST_2018:
        required: false
        type: string
      VALIDATE_RUST_2021:
        required: false
        type: string
      VALIDATE_RUST_2024:
        required: false
        type: string
      VALIDATE_RUST_CLIPPY:
        required: false
        type: string
      VALIDATE_SCALAFMT:
        required: false
        type: string
      VALIDATE_SHELL_SHFMT:
        required: false
        type: string
        default: "false"
      VALIDATE_SNAKEMAKE_LINT:
        required: false
        type: string
      VALIDATE_SNAKEMAKE_SNAKEFMT:
        required: false
        type: string
      VALIDATE_SPELL_CODESPELL:
        required: false
        type: string
      VALIDATE_STATES:
        required: false
        type: string
      VALIDATE_SQL:
        required: false
        type: string
      VALIDATE_SQLFLUFF:
        required: false
        type: string
      VALIDATE_TEKTON:
        required: false
        type: string
      VALIDATE_TERRAFORM_FMT:
        required: false
        type: string
      VALIDATE_TERRAFORM_TERRASCAN:
        required: false
        type: string
      VALIDATE_TERRAFORM_TFLINT:
        required: false
        type: string
      VALIDATE_TERRAGRUNT:
        required: false
        type: string
      VALIDATE_TRIVY:
        required: false
        type: string
      VALIDATE_TSX:
        required: false
        type: string
      VALIDATE_TYPESCRIPT_ES:
        required: false
        type: string
      VALIDATE_TYPESCRIPT_STANDARD:
        required: false
        type: string
      VALIDATE_TYPESCRIPT_PRETTIER:
        required: false
        type: string
      VALIDATE_VUE:
        required: false
        type: string
      VALIDATE_VUE_PRETTIER:
        required: false
        type: string
      VALIDATE_XML:
        required: false
        type: string
      VALIDATE_YAML:
        required: false
        type: string
      VALIDATE_YAML_PRETTIER:
        required: false
        type: string
        default: "false"
      VALIDATE_ALL_CODEBASE:
        required: false
        type: string
    # secrets:
    #   token:
    #     required: true

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  Lint:
    name: Lint Code Base
    runs-on: ubuntu-22.04 # ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Checkout dennykorsukewitz
        uses: actions/checkout@v6
        with:
          fetch-depth: "1"
          repository: dennykorsukewitz/dennykorsukewitz
          ref: "dev"
          path: linters

      - name: Prepare linters config
        run: cp -R "${GITHUB_WORKSPACE}"/linters/.github/linters "${GITHUB_WORKSPACE}"/.github/

      - name: Remove dennykorsukewitz directory
        run: rm -Rf "${GITHUB_WORKSPACE}"/linters

      - name: Check GITHUB_WORKSPACE
        run: |
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "repository: ${GITHUB_WORKSPACE}/repository"
          echo "dennykorsukewitz: ${GITHUB_WORKSPACE}/dennykorsukewitz"
          ls -lahi "${GITHUB_WORKSPACE}"

      - name: Branch Name
        run: echo running on branch "${GITHUB_REF##*/}"

      - name: Show linters config
        run: ls -alih "${GITHUB_WORKSPACE}/.github/linters"

      - name: Set environment variables
        run: |
          if [[ "${{ inputs.VALIDATE_ANSIBLE }}" == "true" ]]; then
            echo "VALIDATE_ANSIBLE=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_ANSIBLE=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_ARM }}" == "true" ]]; then
            echo "VALIDATE_ARM=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_ARM=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_BASH }}" == "true" ]]; then
            echo "VALIDATE_BASH=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_BASH=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_BASH_EXEC }}" == "true" ]]; then
            echo "VALIDATE_BASH_EXEC=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_BASH_EXEC=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_BIOME_FORMAT }}" == "true" ]]; then
            echo "VALIDATE_BIOME_FORMAT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_BIOME_FORMAT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_BIOME_LINT }}" == "true" ]]; then
            echo "VALIDATE_BIOME_LINT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_BIOME_LINT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_CPP }}" == "true" ]]; then
            echo "VALIDATE_CPP=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_CPP=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_CHECKOV }}" == "true" ]]; then
            echo "VALIDATE_CHECKOV=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_CHECKOV=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_CLANG_FORMAT }}" == "true" ]]; then
            echo "VALIDATE_CLANG_FORMAT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_CLANG_FORMAT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_CLOJURE }}" == "true" ]]; then
            echo "VALIDATE_CLOJURE=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_CLOJURE=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_CLOUDFORMATION }}" == "true" ]]; then
            echo "VALIDATE_CLOUDFORMATION=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_CLOUDFORMATION=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_COFFEESCRIPT }}" == "true" ]]; then
            echo "VALIDATE_COFFEESCRIPT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_COFFEESCRIPT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_CSHARP }}" == "true" ]]; then
            echo "VALIDATE_CSHARP=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_CSHARP=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_CSS }}" == "true" ]]; then
            echo "VALIDATE_CSS=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_CSS=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_CSS_PRETTIER }}" == "true" ]]; then
            echo "VALIDATE_CSS_PRETTIER=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_CSS_PRETTIER=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_DART }}" == "true" ]]; then
            echo "VALIDATE_DART=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_DART=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_DOCKERFILE_HADOLINT }}" == "true" ]]; then
            echo "VALIDATE_DOCKERFILE_HADOLINT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_DOCKERFILE_HADOLINT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_DOTNET_SLN_FORMAT_ANALYZERS }}" == "true" ]]; then
            echo "VALIDATE_DOTNET_SLN_FORMAT_ANALYZERS=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_DOTNET_SLN_FORMAT_ANALYZERS=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_DOTNET_SLN_FORMAT_STYLE }}" == "true" ]]; then
            echo "VALIDATE_DOTNET_SLN_FORMAT_STYLE=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_DOTNET_SLN_FORMAT_STYLE=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_DOTNET_SLN_FORMAT_WHITESPACE }}" == "true" ]]; then
            echo "VALIDATE_DOTNET_SLN_FORMAT_WHITESPACE=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_DOTNET_SLN_FORMAT_WHITESPACE=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_EDITORCONFIG }}" == "true" ]]; then
            echo "VALIDATE_EDITORCONFIG=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_EDITORCONFIG=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_ENV }}" == "true" ]]; then
            echo "VALIDATE_ENV=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_ENV=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_GIT_COMMITLINT }}" == "true" ]]; then
            echo "VALIDATE_GIT_COMMITLINT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_GIT_COMMITLINT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_GIT_MERGE_CONFLICT_MARKERS }}" == "true" ]]; then
            echo "VALIDATE_GIT_MERGE_CONFLICT_MARKERS=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_GIT_MERGE_CONFLICT_MARKERS=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_GHERKIN }}" == "true" ]]; then
            echo "VALIDATE_GHERKIN=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_GHERKIN=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_GITHUB_ACTIONS }}" == "true" ]]; then
            echo "VALIDATE_GITHUB_ACTIONS=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_GITHUB_ACTIONS=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_GITHUB_ACTIONS_ZIZMOR }}" == "true" ]]; then
            echo "VALIDATE_GITHUB_ACTIONS_ZIZMOR=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_GITHUB_ACTIONS_ZIZMOR=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_GITLEAKS }}" == "true" ]]; then
            echo "VALIDATE_GITLEAKS=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_GITLEAKS=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_GO }}" == "true" ]]; then
            echo "VALIDATE_GO=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_GO=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_GO_MODULES }}" == "true" ]]; then
            echo "VALIDATE_GO_MODULES=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_GO_MODULES=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_GO_RELEASER }}" == "true" ]]; then
            echo "VALIDATE_GO_RELEASER=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_GO_RELEASER=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_GOOGLE_JAVA_FORMAT }}" == "true" ]]; then
            echo "VALIDATE_GOOGLE_JAVA_FORMAT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_GOOGLE_JAVA_FORMAT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_GRAPHQL_PRETTIER }}" == "true" ]]; then
            echo "VALIDATE_GRAPHQL_PRETTIER=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_GRAPHQL_PRETTIER=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_GROOVY }}" == "true" ]]; then
            echo "VALIDATE_GROOVY=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_GROOVY=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_HTML }}" == "true" ]]; then
            echo "VALIDATE_HTML=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_HTML=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_HTML_PRETTIER }}" == "true" ]]; then
            echo "VALIDATE_HTML_PRETTIER=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_HTML_PRETTIER=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_JAVA }}" == "true" ]]; then
            echo "VALIDATE_JAVA=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_JAVA=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_JAVASCRIPT_ES }}" == "true" ]]; then
            echo "VALIDATE_JAVASCRIPT_ES=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_JAVASCRIPT_ES=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_JAVASCRIPT_PRETTIER }}" == "true" ]]; then
            echo "VALIDATE_JAVASCRIPT_PRETTIER=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_JAVASCRIPT_PRETTIER=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_JAVASCRIPT_STANDARD }}" == "true" ]]; then
            echo "VALIDATE_JAVASCRIPT_STANDARD=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_JAVASCRIPT_STANDARD=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_JSCPD }}" == "true" ]]; then
            echo "VALIDATE_JSCPD=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_JSCPD=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_JSON }}" == "true" ]]; then
            echo "VALIDATE_JSON=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_JSON=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_JSON_PRETTIER }}" == "true" ]]; then
            echo "VALIDATE_JSON_PRETTIER=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_JSON_PRETTIER=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_JSONC }}" == "true" ]]; then
            echo "VALIDATE_JSONC=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_JSONC=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_JSONC_PRETTIER }}" == "true" ]]; then
            echo "VALIDATE_JSONC_PRETTIER=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_JSONC_PRETTIER=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_JSX }}" == "true" ]]; then
            echo "VALIDATE_JSX=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_JSX=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_JSX_PRETTIER }}" == "true" ]]; then
            echo "VALIDATE_JSX_PRETTIER=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_JSX_PRETTIER=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_JUPYTER_NBQA_BLACK }}" == "true" ]]; then
            echo "VALIDATE_JUPYTER_NBQA_BLACK=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_JUPYTER_NBQA_BLACK=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_JUPYTER_NBQA_FLAKE8 }}" == "true" ]]; then
            echo "VALIDATE_JUPYTER_NBQA_FLAKE8=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_JUPYTER_NBQA_FLAKE8=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_JUPYTER_NBQA_ISORT }}" == "true" ]]; then
            echo "VALIDATE_JUPYTER_NBQA_ISORT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_JUPYTER_NBQA_ISORT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_JUPYTER_NBQA_MYPY }}" == "true" ]]; then
            echo "VALIDATE_JUPYTER_NBQA_MYPY=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_JUPYTER_NBQA_MYPY=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_JUPYTER_NBQA_PYLINT }}" == "true" ]]; then
            echo "VALIDATE_JUPYTER_NBQA_PYLINT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_JUPYTER_NBQA_PYLINT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_JUPYTER_NBQA_RUFF }}" == "true" ]]; then
            echo "VALIDATE_JUPYTER_NBQA_RUFF=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_JUPYTER_NBQA_RUFF=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_KOTLIN }}" == "true" ]]; then
            echo "VALIDATE_KOTLIN=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_KOTLIN=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_KOTLIN_ANDROID }}" == "true" ]]; then
            echo "VALIDATE_KOTLIN_ANDROID=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_KOTLIN_ANDROID=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_KUBERNETES_KUBECONFORM }}" == "true" ]]; then
            echo "VALIDATE_KUBERNETES_KUBECONFORM=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_KUBERNETES_KUBECONFORM=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_LATEX }}" == "true" ]]; then
            echo "VALIDATE_LATEX=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_LATEX=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_LUA }}" == "true" ]]; then
            echo "VALIDATE_LUA=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_LUA=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_MARKDOWN }}" == "true" ]]; then
            echo "VALIDATE_MARKDOWN=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_MARKDOWN=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_MARKDOWN_PRETTIER }}" == "true" ]]; then
            echo "VALIDATE_MARKDOWN_PRETTIER=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_MARKDOWN_PRETTIER=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_NATURAL_LANGUAGE }}" == "true" ]]; then
            echo "VALIDATE_NATURAL_LANGUAGE=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_NATURAL_LANGUAGE=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_OPENAPI }}" == "true" ]]; then
            echo "VALIDATE_OPENAPI=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_OPENAPI=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_PERL }}" == "true" ]]; then
            echo "VALIDATE_PERL=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_PERL=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_PHP }}" == "true" ]]; then
            echo "VALIDATE_PHP=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_PHP=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_PHP_BUILTIN }}" == "true" ]]; then
            echo "VALIDATE_PHP_BUILTIN=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_PHP_BUILTIN=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_PHP_PHPCS }}" == "true" ]]; then
            echo "VALIDATE_PHP_PHPCS=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_PHP_PHPCS=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_PHP_PHPSTAN }}" == "true" ]]; then
            echo "VALIDATE_PHP_PHPSTAN=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_PHP_PHPSTAN=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_PHP_PSALM }}" == "true" ]]; then
            echo "VALIDATE_PHP_PSALM=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_PHP_PSALM=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_PRE_COMMIT }}" == "true" ]]; then
            echo "VALIDATE_PRE_COMMIT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_PRE_COMMIT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_POWERSHELL }}" == "true" ]]; then
            echo "VALIDATE_POWERSHELL=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_POWERSHELL=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_PROTOBUF }}" == "true" ]]; then
            echo "VALIDATE_PROTOBUF=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_PROTOBUF=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_PYTHON }}" == "true" ]]; then
            echo "VALIDATE_PYTHON=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_PYTHON=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_PYTHON_BLACK }}" == "true" ]]; then
            echo "VALIDATE_PYTHON_BLACK=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_PYTHON_BLACK=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_PYTHON_FLAKE8 }}" == "true" ]]; then
            echo "VALIDATE_PYTHON_FLAKE8=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_PYTHON_FLAKE8=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_PYTHON_ISORT }}" == "true" ]]; then
            echo "VALIDATE_PYTHON_ISORT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_PYTHON_ISORT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_PYTHON_MYPY }}" == "true" ]]; then
            echo "VALIDATE_PYTHON_MYPY=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_PYTHON_MYPY=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_PYTHON_PYLINT }}" == "true" ]]; then
            echo "VALIDATE_PYTHON_PYLINT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_PYTHON_PYLINT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_PYTHON_RUFF }}" == "true" ]]; then
            echo "VALIDATE_PYTHON_RUFF=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_PYTHON_RUFF=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_PYTHON_RUFF_FORMAT }}" == "true" ]]; then
            echo "VALIDATE_PYTHON_RUFF_FORMAT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_PYTHON_RUFF_FORMAT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_R }}" == "true" ]]; then
            echo "VALIDATE_R=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_R=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_RAKU }}" == "true" ]]; then
            echo "VALIDATE_RAKU=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_RAKU=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_RENOVATE }}" == "true" ]]; then
            echo "VALIDATE_RENOVATE=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_RENOVATE=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_RUBY }}" == "true" ]]; then
            echo "VALIDATE_RUBY=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_RUBY=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_RUST_2015 }}" == "true" ]]; then
            echo "VALIDATE_RUST_2015=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_RUST_2015=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_RUST_2018 }}" == "true" ]]; then
            echo "VALIDATE_RUST_2018=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_RUST_2018=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_RUST_2021 }}" == "true" ]]; then
            echo "VALIDATE_RUST_2021=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_RUST_2021=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_RUST_2024 }}" == "true" ]]; then
            echo "VALIDATE_RUST_2024=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_RUST_2024=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_RUST_CLIPPY }}" == "true" ]]; then
            echo "VALIDATE_RUST_CLIPPY=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_RUST_CLIPPY=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_SCALAFMT }}" == "true" ]]; then
            echo "VALIDATE_SCALAFMT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_SCALAFMT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_SHELL_SHFMT }}" == "true" ]]; then
            echo "VALIDATE_SHELL_SHFMT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_SHELL_SHFMT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_SNAKEMAKE_LINT }}" == "true" ]]; then
            echo "VALIDATE_SNAKEMAKE_LINT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_SNAKEMAKE_LINT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_SNAKEMAKE_SNAKEFMT }}" == "true" ]]; then
            echo "VALIDATE_SNAKEMAKE_SNAKEFMT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_SNAKEMAKE_SNAKEFMT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_SPELL_CODESPELL }}" == "true" ]]; then
            echo "VALIDATE_SPELL_CODESPELL=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_SPELL_CODESPELL=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_STATES }}" == "true" ]]; then
            echo "VALIDATE_STATES=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_STATES=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_SQL }}" == "true" ]]; then
            echo "VALIDATE_SQL=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_SQL=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_SQLFLUFF }}" == "true" ]]; then
            echo "VALIDATE_SQLFLUFF=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_SQLFLUFF=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_TEKTON }}" == "true" ]]; then
            echo "VALIDATE_TEKTON=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_TEKTON=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_TERRAFORM_FMT }}" == "true" ]]; then
            echo "VALIDATE_TERRAFORM_FMT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_TERRAFORM_FMT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_TERRAFORM_TERRASCAN }}" == "true" ]]; then
            echo "VALIDATE_TERRAFORM_TERRASCAN=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_TERRAFORM_TERRASCAN=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_TERRAFORM_TFLINT }}" == "true" ]]; then
            echo "VALIDATE_TERRAFORM_TFLINT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_TERRAFORM_TFLINT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_TERRAGRUNT }}" == "true" ]]; then
            echo "VALIDATE_TERRAGRUNT=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_TERRAGRUNT=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_TRIVY }}" == "true" ]]; then
            echo "VALIDATE_TRIVY=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_TRIVY=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_TSX }}" == "true" ]]; then
            echo "VALIDATE_TSX=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_TSX=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_TYPESCRIPT_ES }}" == "true" ]]; then
            echo "VALIDATE_TYPESCRIPT_ES=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_TYPESCRIPT_ES=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_TYPESCRIPT_STANDARD }}" == "true" ]]; then
            echo "VALIDATE_TYPESCRIPT_STANDARD=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_TYPESCRIPT_STANDARD=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_TYPESCRIPT_PRETTIER }}" == "true" ]]; then
            echo "VALIDATE_TYPESCRIPT_PRETTIER=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_TYPESCRIPT_PRETTIER=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_VUE }}" == "true" ]]; then
            echo "VALIDATE_VUE=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_VUE=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_VUE_PRETTIER }}" == "true" ]]; then
            echo "VALIDATE_VUE_PRETTIER=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_VUE_PRETTIER=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_XML }}" == "true" ]]; then
            echo "VALIDATE_XML=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_XML=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_YAML }}" == "true" ]]; then
            echo "VALIDATE_YAML=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_YAML=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_YAML_PRETTIER }}" == "true" ]]; then
            echo "VALIDATE_YAML_PRETTIER=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_YAML_PRETTIER=false" >> "$GITHUB_ENV"
          fi
          if [[ "${{ inputs.VALIDATE_ALL_CODEBASE }}" == "true" ]]; then
            echo "VALIDATE_ALL_CODEBASE=true" >> "$GITHUB_ENV"
          else
            echo "VALIDATE_ALL_CODEBASE=false" >> "$GITHUB_ENV"
          fi

          echo "Environment variables set:"
          cat "$GITHUB_ENV"

      - name: Lint Code Base
        uses: super-linter/super-linter@v8.5.0
        env:
          GITHUB_TOKEN: "${secrets.GITHUB_TOKEN}"
          LINTER_RULES_PATH: "./.github/linters"
          USE_FIND_ALGORITHM: true
          FILTER_REGEX_EXCLUDE: "(.*.scss)"
          IGNORE_GITIGNORED_FILES: true
          DEFAULT_WORKSPACE: "${GITHUB_WORKSPACE}"

          # Test
          GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

          # Disable specific linters
