---
name: Lint

on:
  workflow_call:
    inputs:
      VALIDATE_PYTHON_MYPY
        required: false
        type: boolean
        default: 'false'
      VALIDATE_JSCPD
        required: false
        type: boolean
        default: 'false'
      VALIDATE_POWERSHELL
        required: false
        type: boolean
        default: 'false'
      VALIDATE_JAVASCRIPT_STANDARD
        required: false
        type: boolean
        default: 'false'

    # secrets:
    #   token:
    #     required: true

jobs:
  Lint:
    name: Lint Code Base
    runs-on: ubuntu-22.04 # ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        env:
          fetch-depth: "1"
        with:
          path: repository

      - name: Check out dennykorsukewitz
        uses: actions/checkout@v3
        env:
          fetch-depth: "1"
        with:
          repository: dennykorsukewitz/dennykorsukewitz
          ref: 'dev'
          path: ./../dennykorsukewitz

      - name: Prepare linters config
        run: cp -R "${GITHUB_WORKSPACE}"/../dennykorsukewitz/.github/linters "${GITHUB_WORKSPACE}"/repository/.github/

      - name: Branch Name
        run: echo running on branch "${GITHUB_REF##*/}"

      - name: Show linters config
        run: ls -alih "${GITHUB_WORKSPACE}/repository/.github/linters"

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: "${GITHUB_REF##*/}"
          GITHUB_TOKEN: "${secrets.GITHUB_TOKEN}"
          LINTER_RULES_PATH: "./repository/.github/linters"
          USE_FIND_ALGORITHM: true
          FILTER_REGEX_EXCLUDE: "(.*.scss)"
          IGNORE_GITIGNORED_FILES: true
          DEFAULT_WORKSPACE: "${GITHUB_WORKSPACE}/repository"

          VALIDATE_PYTHON_MYPY: ${{ inputs.VALIDATE_PYTHON_MYPY }}
          VALIDATE_JSCPD: ${{ inputs.VALIDATE_JSCPD }}
          VALIDATE_POWERSHELL: ${{ inputs.VALIDATE_POWERSHELL }}
          VALIDATE_JAVASCRIPT_STANDARD: ${{ inputs.VALIDATE_JAVASCRIPT_STANDARD }}
