---
name: Sync Fork

on:
  # Schedule updates (“At 00:00.”)
  schedule:
    # "0 0 * * *" (UTC) = "0 1 * * *" (Germany)
    - cron: "0 0 * * *"

  workflow_dispatch:
    inputs:
      SOURCE_REPO:
        description: "Source repository. (e.g. upptime/upptime)"
        required: false
        type: string
      DESTINATION_REPO:
        description: "Destination repository. (e.g. dennykorsukewitz/upptime)"
        required: false
        type: string
      BRANCH:
        description: "Branch name. (e.g. main)"
        required: false
        type: string

jobs:
  Upptime:
    strategy:
      matrix:
        BRANCH: [master, gh-pages]
    uses: dennykorsukewitz/dennykorsukewitz/.github/workflows/sync.yml@dev
    with:
      SOURCE_REPO: ${{ inputs.SOURCE_REPO || 'upptime/upptime' }}
      DESTINATION_REPO: ${{ inputs.DESTINATION_REPO || 'dennykorsukewitz/upptime' }}
      BRANCH: ${{ inputs.BRANCH || matrix.BRANCH }}
    secrets:
      PAT: ${{ secrets.PAT }}
