---
name: Workflow

on:
  workflow_dispatch:
    inputs:
      FUNCTION:
        description: "Which function should I perform?"
        required: true
        default: "delete failed"
        type: choice
        options:
          - "delete all"
          - "delete failed"
          - "list all"
          - "list failed"
      OWNER:
        description: "Owner"
        required: true
        type: string
        default: "dennykorsukewitz"
      REPOSITORY:
        description: "Repository"
        required: true
        type: string
        default: "dennykorsukewitz"
      WORKFLOW_NAME:
        description: "Workflow, if not specified all workflows will be used."
        required: false
        type: string

jobs:
  List_All:
    name: List all workflow runs
    runs-on: ubuntu-22.04
    if: ${{ github.event.inputs.FUNCTION == 'list all' }}
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: List workflow runs
        run: |
          if [ "${{ inputs.WORKFLOW_NAME }}" = "" ]; then

            mapfile -t WORKFLOW_IDs < <(gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows | jq '.workflows[] | .id')
            echo "${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}"
          else

            mapfile -t WORKFLOW_IDs < <(gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows | jq '.workflows[] | select(.name=="${{ inputs.WORKFLOW_NAME }}") | .id')
            echo "${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}: ${{ inputs.WORKFLOW_NAME }}"
          fi

          for WORKFLOW_ID in "${WORKFLOW_IDs[@]}"; do
            echo "Workflow ID: $WORKFLOW_ID"
            gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows/"$WORKFLOW_ID"/runs --paginate | jq '.workflow_runs[] | .id'
          done

  List_Failed:
    name: List failed workflow runs
    runs-on: ubuntu-22.04
    if: ${{ github.event.inputs.FUNCTION == 'list failed' }}
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: List failed workflow runs
        run: |
          if [ "${{ inputs.WORKFLOW_NAME }}" = "" ]; then

            mapfile -t WORKFLOW_IDs < <(gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows | jq '.workflows[] | .id')
            echo "${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}"
          else

            mapfile -t WORKFLOW_IDs < <(gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows | jq '.workflows[] | select(.name=="${{ inputs.WORKFLOW_NAME }}") | .id')
            echo "${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}: ${{ inputs.WORKFLOW_NAME }}"
          fi

          for WORKFLOW_ID in "${WORKFLOW_IDs[@]}"; do
            echo "Wor"
            gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows/"$WORKFLOW_ID"/runs --paginate | jq '.workflow_runs[] | select(.conclusion=="failure") | .id'
          done

  Delete_All:
    name: Delete all workflow runs
    runs-on: ubuntu-22.04
    if: ${{ github.event.inputs.FUNCTION == 'delete all' }}
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: Delete all workflow runs
        run: |
          if [ "${{ inputs.WORKFLOW_NAME }}" = "" ]; then

            mapfile -t WORKFLOW_IDs < <(gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows | jq '.workflows[] | .id')
            echo "${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}"
          else

            mapfile -t WORKFLOW_IDs < <(gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows | jq '.workflows[] | select(.name=="${{ inputs.WORKFLOW_NAME }}") | .id')
            echo "${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}: ${{ inputs.WORKFLOW_NAME }}"
          fi

          for WORKFLOW_ID in "${WORKFLOW_IDs[@]}"; do
            echo "Wor"
            gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows/"$WORKFLOW_ID"/runs --paginate | jq '.workflow_runs[] | .id' | xargs -I{} gh api -X DELETE /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/runs/{} --silent
          done

  Delete_Failed:
    name: Delete failed workflow runs
    runs-on: ubuntu-22.04
    if: ${{ github.event.inputs.FUNCTION == 'delete failed' }}
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: Delete failed workflow runs
        run: |
          if [ "${{ inputs.WORKFLOW_NAME }}" = "" ]; then

            mapfile -t WORKFLOW_IDs < <(gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows | jq '.workflows[] | .id')
            echo "${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}"
          else

            mapfile -t WORKFLOW_IDs < <(gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows | jq '.workflows[] | select(.name=="${{ inputs.WORKFLOW_NAME }}") | .id')
            echo "${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}: ${{ inputs.WORKFLOW_NAME }}"
          fi

          for WORKFLOW_ID in "${WORKFLOW_IDs[@]}"; do
            echo "Wor"

            gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows/"$WORKFLOW_ID"/runs --paginate | jq '.workflow_runs[] | select(.conclusion=="failure") | .id' | xargs -I{} gh api -X DELETE /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/runs/{} --silent
          done
