---
name: Workflow

on:
  workflow_dispatch:
    inputs:
      FUNCTION:
        description: "Which function should I perform?"
        required: true
        default: "list_failed"
        type: choice
        options:
          - "delete all"
          - "delete failed"
          - "list all"
          - "list failed"
      OWNER:
        description: "Owner"
        required: true
        type: string
        default: "dennykorsukewitz"
      REPOSITORY:
        description: "Repository"
        required: true
        type: string
        default: "dennykorsukewitz"
      WORKFLOW_NAME:
        description: "Workflow, if not specified all workflows will be used."
        required: false
        type: string

jobs:
  List_All:
    name: List all workflow runs
    runs-on: ubuntu-22.04
    if: ${{ github.event.inputs.FUNCTION == 'list all' }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: List workflow runs
        run: |
          if [[ "${{ inputs.WORKFLOW_NAME }}" == "" ]]; then

            WORKFLOW_IDs=($(gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows | jq '.workflows[] | .id'))
            echo "${{ inputs.OWNER }}/${{ inputs.REPOSITORY }} ($WORKFLOW_IDs)"
          else

            WORKFLOW_IDs=($(gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows | jq '.workflows[] | select(.name=="${{ inputs.WORKFLOW_NAME }}") | .id'))
            echo "${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}: ${{ inputs.WORKFLOW_NAME }} ($WORKFLOW_IDs)"
          fi

          for WORKFLOW_ID in "$WORKFLOW_IDs"; do
            gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows/$WORKFLOW_ID/runs --paginate | jq '.workflow_runs[] | .id'
          done

  List_Failed:
    name: List failed workflow runs
    runs-on: ubuntu-22.04
    if: ${{ github.event.inputs.FUNCTION == 'list failed' }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: List failed workflow runs
        run: |
          if [[ "${{ inputs.WORKFLOW_NAME }}" == "" ]]; then

            WORKFLOW_IDs=($(gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows | jq '.workflows[] | .id'))
            echo "${{ inputs.OWNER }}/${{ inputs.REPOSITORY }} ($WORKFLOW_IDs)"
          else

            WORKFLOW_IDs=($(gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows | jq '.workflows[] | select(.name=="${{ inputs.WORKFLOW_NAME }}") | .id'))
            echo "${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}: ${{ inputs.WORKFLOW_NAME }} ($WORKFLOW_IDs)"
          fi

          for WORKFLOW_ID in "$WORKFLOW_IDs"; do
            gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows/$WORKFLOW_ID/runs --paginate | jq '.workflow_runs[] | select(.conclusion=="failure") | .id'
          done

  Delete_All:
    name: Delete all workflow runs
    runs-on: ubuntu-22.04
    if: ${{ github.event.inputs.FUNCTION == 'delete all' }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Delete all workflow runs
        run: |
          if [[ "${{ inputs.WORKFLOW_NAME }}" == "" ]]; then

            WORKFLOW_IDs=($(gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows | jq '.workflows[] | .id'))
            echo "${{ inputs.OWNER }}/${{ inputs.REPOSITORY }} ($WORKFLOW_IDs)"
          else

            WORKFLOW_IDs=($(gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows | jq '.workflows[] | select(.name=="${{ inputs.WORKFLOW_NAME }}") | .id'))
            echo "${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}: ${{ inputs.WORKFLOW_NAME }} ($WORKFLOW_IDs)"
          fi

          for WORKFLOW_ID in "$WORKFLOW_IDs"; do
            gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows/$WORKFLOW_ID/runs --paginate | jq '.workflow_runs[] | .id' | xargs -I{} gh api -X DELETE /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/runs/{} --silent
          done

  Delete_Failed:
    name: Delete failed workflow runs
    runs-on: ubuntu-22.04
    if: ${{ github.event.inputs.FUNCTION == 'delete failed' }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Delete failed workflow runs
        run: |
          if [[ "${{ inputs.WORKFLOW_NAME }}" == "" ]]; then

            WORKFLOW_IDs=($(gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows | jq '.workflows[] | .id'))
            echo "${{ inputs.OWNER }}/${{ inputs.REPOSITORY }} ($WORKFLOW_IDs)"
          else

            WORKFLOW_IDs=($(gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows | jq '.workflows[] | select(.name=="${{ inputs.WORKFLOW_NAME }}") | .id'))
            echo "${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}: ${{ inputs.WORKFLOW_NAME }} ($WORKFLOW_IDs)"
          fi

          for WORKFLOW_ID in "$WORKFLOW_IDs"; do

            gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows/$WORKFLOW_ID/runs --paginate | jq '.workflow_runs[] | select(.conclusion=="failure") | .id' | xargs -I{} gh api -X DELETE /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/runs/{} --silent
          done
